# Generated by Django 4.1 on 2022-09-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True)),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.CharField(max_length=4)),
                ('data_cadastro', models.DateField()),
                ('numero_paginas', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
